project_id = "kzxqeagnrlhyvijylkxp"

[functions.send-email]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false

[functions.generate-email]
verify_jwt = false

[functions.generate-persona]
verify_jwt = false

[functions.send-campaign-emails]
verify_jwt = false